#VERSION:1.2
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zuul-springcloud
  namespace: springcloud
  labels:
    app: zuul-springcloud
spec:
  serviceName: zuul-springcloud
  selector:
    matchLabels:
      app: zuul-springcloud
  replicas: 1
  template:
    metadata:
      name: zuul-springcloud
      labels:
        app: zuul-springcloud
    spec:
      serviceAccountName: sa-springcloud
      containers:
      - name: zuul-springcloud
        image: harbor.io/springcloud/zuul-springcloud:0.0.1
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: "8080" 
        - name: PROFILE
          value: dev
        envFrom:
        - configMapRef:
            name: "zuul-springcloud-cm"        
        - secretRef:
            name: "zuul-springcloud-secret"           
        ports:
        - name: containerport
          containerPort: 8080
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-springcloud
  namespace: springcloud  
spec:
  type: ClusterIP
  selector:
    app: zuul-springcloud
  ports:
  - name: port1
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: zuul-springcloud
  namespace: springcloud  
spec:
  rules:
  - host: {{ SERVICE_HOST }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: zuul-springcloud 
            port: 
              number: 8080
